In [ ]:
import holidays
from datetime import date

# Configurar los festivos de Estados Unidos en español (interfaz compatible)
us_holidays = holidays.US(years=range(2022, 2026), language="es")

# Imprimir todas las festividades encontradas
for fecha, nombre in sorted(us_holidays.items()):
    print(f"{fecha}: {nombre}")

2022-01-01: New Year's Day
2022-01-17: Martin Luther King Jr. Day
2022-02-21: Washington's Birthday
2022-05-30: Memorial Day
2022-06-19: Juneteenth National Independence Day
2022-06-20: Juneteenth National Independence Day (observed)
2022-07-04: Independence Day
2022-09-05: Labor Day
2022-10-10: Columbus Day
2022-11-11: Veterans Day
2022-11-24: Thanksgiving Day
2022-12-25: Christmas Day
2022-12-26: Christmas Day (observed)
2023-01-01: New Year's Day
2023-01-02: New Year's Day (observed)
2023-01-16: Martin Luther King Jr. Day
2023-02-20: Washington's Birthday
2023-05-29: Memorial Day
2023-06-19: Juneteenth National Independence Day
2023-07-04: Independence Day
2023-09-04: Labor Day
2023-10-09: Columbus Day
2023-11-10: Veterans Day (observed)
2023-11-11: Veterans Day
2023-11-23: Thanksgiving Day
2023-12-25: Christmas Day
2024-01-01: New Year's Day
2024-01-15: Martin Luther King Jr. Day
2024-02-19: Washington's Birthday
2024-05-27: Memorial Day
2024-06-19: Juneteenth National Independence Day
2024-07-04: Independence Day
2024-09-02: Labor Day
2024-10-14: Columbus Day
2024-11-11: Veterans Day
2024-11-28: Thanksgiving Day
2024-12-25: Christmas Day
2025-01-01: New Year's Day
2025-01-20: Martin Luther King Jr. Day
2025-02-17: Washington's Birthday
2025-05-26: Memorial Day
2025-06-19: Juneteenth National Independence Day
2025-07-04: Independence Day
2025-09-01: Labor Day
2025-10-13: Columbus Day
2025-11-11: Veterans Day
2025-11-27: Thanksgiving Day
2025-12-25: Christmas Day

 festividades de un estado específico, como California

In [ ]:
import holidays

# Configurar los festivos de California (USA) en español para los años 2022-2025
ca_holidays = holidays.US(years=range(2022, 2026), state='CA', language='es')

# Imprimir todas las festividades de California encontradas
print("\nFestividades de California (2022-2025):")
for fecha, nombre in sorted(ca_holidays.items()):
    print(f"{fecha}: {nombre}")

Festividades de California (2022-2025):
2022-01-01: New Year's Day
2022-01-17: Martin Luther King Jr. Day
2022-02-15: Susan B. Anthony Day
2022-02-21: Presidents' Day
2022-03-31: Cesar Chavez Day
2022-05-30: Memorial Day
2022-06-19: Juneteenth National Independence Day
2022-06-20: Juneteenth National Independence Day (observed)
2022-07-04: Independence Day
2022-09-05: Labor Day
2022-11-11: Veterans Day
2022-11-24: Thanksgiving Day
2022-11-25: Day After Thanksgiving
2022-12-25: Christmas Day
2022-12-26: Christmas Day (observed)
2023-01-01: New Year's Day
2023-01-02: New Year's Day (observed)
2023-01-16: Martin Luther King Jr. Day
2023-02-15: Susan B. Anthony Day
2023-02-20: Presidents' Day
2023-03-31: Cesar Chavez Day
2023-05-29: Memorial Day
2023-06-19: Juneteenth National Independence Day
2023-07-04: Independence Day
2023-09-04: Labor Day
2023-11-10: Veterans Day (observed)
2023-11-11: Veterans Day
2023-11-23: Thanksgiving Day
2023-11-24: Day After Thanksgiving
2023-12-25: Christmas Day
2024-01-01: New Year's Day
2024-01-15: Martin Luther King Jr. Day
2024-02-15: Susan B. Anthony Day
2024-02-19: Presidents' Day
2024-03-31: Cesar Chavez Day
2024-04-01: Cesar Chavez Day (observed)
2024-05-27: Memorial Day
2024-06-19: Juneteenth National Independence Day
2024-07-04: Independence Day
2024-09-02: Labor Day
2024-11-11: Veterans Day
2024-11-28: Thanksgiving Day
2024-11-29: Day After Thanksgiving
2024-12-25: Christmas Day
2025-01-01: New Year's Day
2025-01-20: Martin Luther King Jr. Day
2025-02-15: Susan B. Anthony Day
2025-02-17: Presidents' Day
2025-03-31: Cesar Chavez Day
2025-05-26: Memorial Day
2025-06-19: Juneteenth National Independence Day
2025-07-04: Independence Day
2025-09-01: Labor Day
2025-11-11: Veterans Day
2025-11-27: Thanksgiving Day
2025-11-28: Day After Thanksgiving
2025-12-25: Christmas Day

los que dicen(observed) es por que el festivo cayo en un dia que no se trabaja osea en un fin de semana entonces corren el festivo. por eso el año nuevo aparece tanto el 1 de enero y el 2.

In [ ]:
import pandas as pd

# Initialize a list to store holiday data
holiday_data = []

# Add federal holidays
for fecha, nombre in us_holidays.items():
    holiday_data.append({'Fecha': fecha, 'Nombre': nombre, 'Tipo': 'Federal'})

# Add California holidays. We need to check if they are already in federal list to avoid pure duplicates,
# but we also want to mark them as 'California' type.
# A more sophisticated approach would merge, but for now, we'll list both types.
for fecha, nombre in ca_holidays.items():
    # Check if this holiday is already present as a federal holiday
    # This simple check assumes the name and date are sufficient to identify a 'same' holiday
    is_federal_holiday = any(d['Fecha'] == fecha and d['Nombre'] == nombre and d['Tipo'] == 'Federal' for d in holiday_data)

    if is_federal_holiday:
        # If it's also federal, modify the existing entry to include 'California'
        for entry in holiday_data:
            if entry['Fecha'] == fecha and entry['Nombre'] == nombre and entry['Tipo'] == 'Federal':
                entry['Tipo'] = 'Federal, California'
    else:
        # If not federal, add it as a 'California' holiday
        holiday_data.append({'Fecha': fecha, 'Nombre': nombre, 'Tipo': 'California'})

# Create a DataFrame
holidays_df = pd.DataFrame(holiday_data)

# Sort by date
holidays_df['Fecha'] = pd.to_datetime(holidays_df['Fecha'])
holidays_df = holidays_df.sort_values(by='Fecha').reset_index(drop=True)

# Display the first few rows of the combined DataFrame
print("\nCombined Holidays DataFrame:")
display(holidays_df.head())

Combined Holidays DataFrame:

       Fecha                      Nombre                 Tipo
0 2022-01-01              New Year's Day  Federal, California
1 2022-01-17  Martin Luther King Jr. Day  Federal, California
2 2022-02-15        Susan B. Anthony Day           California
3 2022-02-21             Presidents' Day           California
4 2022-02-21       Washington's Birthday              Federal

In [ ]:
# Save the DataFrame to a CSV file
output_csv_path = 'holidays_combined.csv'
holidays_df.to_csv(output_csv_path, index=False)

print(f"\nCombined holidays saved to '{output_csv_path}'")

Combined holidays saved to 'holidays_combined.csv'

Ahora, vamos a generar un archivo CSV que incluya las festividades federales y las de todos los estados de EE. UU. para el rango de años (2022-2025). Combinaremos los datos y marcaremos el origen de cada festividad (Federal, código de estado, o ambos).

In [ ]:
import pandas as pd
import holidays

# Definir el rango de años para el que queremos las festividades
years_range = range(2022, 2026) # Incluye hasta 2025

# --- 1. Obtener festividades federales ---
print("Obteniendo festividades federales...")
us_holidays_federal = holidays.US(years=years_range, language='es')

federal_records = []
for fecha, nombre in us_holidays_federal.items():
    federal_records.append({'Fecha': fecha, 'Nombre': nombre, 'Tipo': 'Federal'})
federal_df = pd.DataFrame(federal_records)

print(f"Se encontraron {len(federal_df)} festividades federales.")

Obteniendo festividades federales...
Se encontraron 48 festividades federales.

In [ ]:
# --- 2. Obtener festividades por estado ---
print("Obteniendo festividades por estado...")

# Obtener la lista de códigos de estados de EE. UU. soportados por la librería holidays
# El método correcto para la clase US es acceder a .subdivisions
us_states_codes = holidays.US.subdivisions

state_holiday_records = []
for state_code in us_states_codes:
    # print(f"  Procesando estado: {state_code}")
    state_holidays = holidays.US(years=years_range, state=state_code, language='es')
    for fecha, nombre in state_holidays.items():
        state_holiday_records.append({'Fecha': fecha, 'Nombre': nombre, 'Tipo': state_code})

state_df = pd.DataFrame(state_holiday_records)
print(f"Se encontraron {len(state_df)} festividades estatales (incluyendo duplicados con federales y entre estados).")

Obteniendo festividades por estado...
Se encontraron 3080 festividades estatales (incluyendo duplicados con federales y entre estados).

In [ ]:
# --- 3. Combinar y limpiar los datos ---
print("Combinando y limpiando los datos...")

# Concatenar los DataFrames federales y estatales
combined_df = pd.concat([federal_df, state_df], ignore_index=True)

# Convertir la columna 'Fecha' a tipo datetime para ordenar
combined_df['Fecha'] = pd.to_datetime(combined_df['Fecha'])

# Agrupar por fecha y nombre para combinar los tipos de festividad
# Usamos `x.unique()` para evitar que se repitan los tipos si un estado tiene el mismo festivo listado varias veces,
# y `sorted()` para mantener un orden consistente en la cadena de tipos.
holidays_all_states_df = combined_df.groupby(['Fecha', 'Nombre'])['Tipo'] \
                                     .apply(lambda x: ', '.join(sorted(x.unique()))) \
                                     .reset_index()

# Ordenar el DataFrame final por fecha
holidays_all_states_df = holidays_all_states_df.sort_values(by='Fecha').reset_index(drop=True)

# Mostrar las primeras filas del DataFrame combinado
print("\nDataFrame de Festividades Combinadas (primeras 10 filas):")
display(holidays_all_states_df.head(10))

# --- 4. Guardar a CSV ---
output_csv_all_states_path = 'holidays_all_us_states_combined.csv'
holidays_all_states_df.to_csv(output_csv_all_states_path, index=False)

print(f"\nTodas las festividades combinadas se han guardado en '{output_csv_all_states_path}'")

Combinando y limpiando los datos...

DataFrame de Festividades Combinadas (primeras 10 filas):

,Fecha,Nombre,Tipo
0,2022-01-01,New Year's Day,"AK, AL, AR, AS, AZ, CA, CO, CT, DC, DE, FL, Fe..."
1,2022-01-06,Epiphany,PR
2,2022-01-06,Three Kings Day,VI
3,2022-01-17,Dr. Martin Luther King Jr. / Civil Rights Day,"AZ, NH"
4,2022-01-17,Dr. Martin Luther King Jr. and Robert E. Lee's...,MS
5,2022-01-17,Martin Luther King Jr. / Idaho Human Rights Day,ID
6,2022-01-17,Martin Luther King Jr. Day,"AR, AS, CA, CO, CT, DC, DE, FL, Federal, GA, G..."
7,2022-01-17,Martin Luther King Jr.'s Birthday,AK
8,2022-01-17,"Martin Luther King, Jr & Robert E. Lee's Birthday",AL
9,2022-01-19,Confederate Memorial Day,TX

Todas las festividades combinadas se han guardado en 'holidays_all_us_states_combined.csv'

Ahora puedes descargar el archivo `holidays_all_us_states_combined.csv` desde tu entorno de Colab.

You can now download the `holidays_combined.csv` file from your Colab environment.

In [ ]:
import holidays
import pandas as pd

years_range = range(2022, 2026)

# --- Festivos federales: aparecen UNA sola vez, incluyendo su "(observed)" si aplica ---
us_holidays_federal = holidays.US(years=years_range)
federal_records = [
    {'Fecha': f, 'Nombre': n, 'Tipo': 'Federal', 'Estado': 'US'}
    for f, n in us_holidays_federal.items()
]
federal_df = pd.DataFrame(federal_records)
print(f"Festivos federales (únicos): {len(federal_df)}")

# clave (Fecha, Nombre) para no repetir festivos federales dentro del loop por estado
federal_keys = set(zip(federal_df['Fecha'], federal_df['Nombre']))

# --- Festivos realmente propios de cada estado (excluye lo que ya es federal) ---
us_states_codes = sorted(holidays.US.subdivisions)
state_records = []
for state_code in us_states_codes:
    state_holidays = holidays.US(years=years_range, state=state_code)
    for fecha, nombre in state_holidays.items():
        if (fecha, nombre) in federal_keys:
            continue  # ya está en federal_df, no lo repetimos
        state_records.append(
            {'Fecha': fecha, 'Nombre': nombre, 'Tipo': 'Estatal', 'Estado': state_code}
        )
state_df = pd.DataFrame(state_records)
print(f"Festivos propios de estados: {len(state_df)}")

# --- Combinar ---
df_holidays = pd.concat([federal_df, state_df], ignore_index=True)

# --- Limpieza de texto y tipos ---
df_holidays['Fecha'] = pd.to_datetime(df_holidays['Fecha'])
df_holidays['Nombre'] = df_holidays['Nombre'].str.strip()
df_holidays['Tipo'] = df_holidays['Tipo'].str.strip()
df_holidays['Estado'] = df_holidays['Estado'].str.strip()

# --- Columnas derivadas ---
df_holidays['Anio'] = df_holidays['Fecha'].dt.year
df_holidays['Mes'] = df_holidays['Fecha'].dt.month
df_holidays['Dia'] = df_holidays['Fecha'].dt.day
df_holidays['DiaSemana'] = df_holidays['Fecha'].dt.day_name()
df_holidays['EsFinDeSemana'] = df_holidays['Fecha'].dt.weekday >= 5
df_holidays['EsObservado'] = df_holidays['Nombre'].str.contains(r'\(observed\)', case=False, regex=True)

# --- Orden final ---
df_holidays = df_holidays[
    ['Fecha', 'Anio', 'Mes', 'Dia', 'DiaSemana', 'Nombre', 'Tipo', 'Estado', 'EsFinDeSemana', 'EsObservado']
].sort_values(['Fecha', 'Tipo', 'Estado']).reset_index(drop=True)

# --- Quitar duplicados exactos (por seguridad) ---
before = len(df_holidays)
df_holidays = df_holidays.drop_duplicates(subset=['Fecha', 'Nombre', 'Tipo', 'Estado'])
print(f"Duplicados exactos eliminados: {before - len(df_holidays)}")

# --- Validaciones ---
null_counts = df_holidays.isnull().sum()
assert null_counts.sum() == 0, f"Hay valores nulos:\n{null_counts[null_counts > 0]}"
assert (df_holidays['Nombre'].str.len() > 0).all(), "Hay nombres vacíos"
assert (df_holidays['Estado'].str.len() > 0).all(), "Hay estados vacíos"
assert set(df_holidays['Tipo'].unique()) <= {'Federal', 'Estatal'}, "Tipo tiene valores inesperados"
fed_dupes = df_holidays[df_holidays.Tipo == 'Federal'].duplicated(subset=['Fecha', 'Nombre']).sum()
assert fed_dupes == 0, "Hay festivos federales repetidos"
print("✔ Sin nulos, sin duplicados, festivos federales únicos")

df_holidays.to_csv('holidays_all_us_states_long.csv', index=False)
print(f"Total filas: {len(df_holidays)}")
print(f"  - Federales: {(df_holidays.Tipo=='Federal').sum()}")
print(f"  - Estatales: {(df_holidays.Tipo=='Estatal').sum()}")
df_holidays.head(15)

Festivos federales (únicos): 48
Festivos propios de estados: 665
Duplicados exactos eliminados: 0
✔ Sin nulos, sin duplicados, festivos federales únicos
Total filas: 713
  - Federales: 48
  - Estatales: 665

,Fecha,Anio,Mes,Dia,DiaSemana,Nombre,Tipo,Estado,EsFinDeSemana,EsObservado
0,2022-01-01,2022,1,1,Saturday,New Year's Day,Federal,US,True,False
1,2022-01-06,2022,1,6,Thursday,Epiphany,Estatal,PR,False,False
2,2022-01-06,2022,1,6,Thursday,Three Kings Day,Estatal,VI,False,False
3,2022-01-17,2022,1,17,Monday,Martin Luther King Jr.'s Birthday,Estatal,AK,False,False
4,2022-01-17,2022,1,17,Monday,"Martin Luther King, Jr & Robert E. Lee's Birthday",Estatal,AL,False,False
5,2022-01-17,2022,1,17,Monday,Dr. Martin Luther King Jr. / Civil Rights Day,Estatal,AZ,False,False
6,2022-01-17,2022,1,17,Monday,Martin Luther King Jr. / Idaho Human Rights Day,Estatal,ID,False,False
7,2022-01-17,2022,1,17,Monday,Dr. Martin Luther King Jr. and Robert E. Lee's...,Estatal,MS,False,False
8,2022-01-17,2022,1,17,Monday,Dr. Martin Luther King Jr. / Civil Rights Day,Estatal,NH,False,False
9,2022-01-17,2022,1,17,Monday,Martin Luther King Jr. Day,Federal,US,False,False
10,2022-01-19,2022,1,19,Wednesday,Confederate Memorial Day,Estatal,TX,False,False
11,2022-02-11,2022,2,11,Friday,Lincoln's Birthday (observed),Estatal,CT,False,True
12,2022-02-11,2022,2,11,Friday,Lincoln's Birthday (observed),Estatal,IA,False,True
13,2022-02-11,2022,2,11,Friday,Lincoln's Birthday (observed),Estatal,IL,False,True
14,2022-02-11,2022,2,11,Friday,Lincoln's Birthday (observed),Estatal,NJ,False,True